### ISSUE TITLE
Item - uncheck Options once "Is Booking Item" is checked

### ISSUE THREAD

**Issue by vrms** [jigartarpara/bookingapp#1]
Once an item is a "Booking Item" it makes not much sense to have the (checked by default) "Maintain Stock" & "Acclow Transfer for Manufacturing" options are checked. Is it possible to have them unchecked automatically once the "Is Booking Item" Option is checked?

![image](https://user-images.githubusercontent.com/7608112/50546003-d3002680-0c20-11e9-9d91-09eab0ddcc9d.png)

**Comment by jigartarpara** [comment]
May be it can useful in case we are also selling item and also giving it on rent so it may case
