### ISSUE TITLE
can't install on a Python3 ERPNext

### ISSUE THREAD

**Issue by vrms** [jigartarpara/bookingapp#2]
as the title says. Seems the `bookingapp` is not working in a python3 version of frappe/erpnext.

I think from v11 onwards python3 is the at least even (if not recommended) python version for ERPNext (performance enhancements are significant I've heard), so I think it would be a good idea to make this p3 ready rather sooner then later.

[this may be useful](http://python-future.org/compatible_idioms.html)

**Comment by jigartarpara** [comment]
I checked it for latest version in master branch and it's working fine
