### ISSUE TITLE
Required Field: Naming Series

### ISSUE THREAD

**Issue by GeorgS** [jigartarpara/bookingapp#3]
After installing and enabling the plugin everything seems to work fine.
But when trying to save a new service item I get an error that a `Naming Series` is required.

Is there something else I need to configure in order for this to work?
Running on ERPnext v12.

**Comment by rithin** [comment]
@GeorgS  You got any workaround for this? Facing the same issue.
@jigartarpara  Can you please post some screenshots of your doctype setting and booking procedure. It will give us an insight on configuring the app correctly.

**Comment by jigartarpara** [comment]
You have to set naming series for doctype Book Service
![Naming Series](https://user-images.githubusercontent.com/11938071/57613722-39b12b80-7595-11e9-8b97-ad66b55dea9b.png)
